from setuptools import setup, find_packages

setup(
name="ragbot",
version="0.1.0",
description="Production-ready RAG bot using Pinecone, OpenAI embeddings, and Groq LLM",
author="Nishant Gupta",
package_dir={"": "src"},
packages=find_packages(where="src"),
python_requires=">=3.11",
install_requires=[
    "fastapi==0.135.1",
    "uvicorn==0.41.0",
    "boto3==1.42.68",
    "numpy==2.4.3",
    "pypdf==6.9.0",
    "python-dotenv==1.2.2",
    "rank-bm25==0.2.2",
    "pydantic==2.12.5",
    "pydantic-settings==2.13.1",
    "pinecone==7.3.0",
    "langchain==1.2.12",
    "langchain-core==1.2.18",
    "langchain-community==0.4.1",
    "langchain-groq==1.1.2",
    "langchain-openai==1.1.11",
    "langchain-pinecone==0.2.13",
    "langchain-text-splitters==1.1.1",
],
)
